// eslint-disable-next-line @next/next/no-img-element
import Aside from "@/components/Aside";
import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import Spinner from "@/components/Spinner";
import Wrapper from "@/components/Wrapper";
import { LoadingContext } from "@/context/LoadingContext";
import { OpenContext } from "@/context/OpenContext";
import Head from "next/head";
import { useContext, useEffect } from "react";

export default function Home() {
  const { loading } = useContext(LoadingContext);
  const { toggleModal, slug } = useContext(OpenContext);
  return (
    <>
      {loading ? <Spinner /> : ""}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="https://argentobourbon.com/cdn/shop/files/Deportivos.png?v=1675700549&width=2400"
        alt="slider"
        className="mb-[30px]"
      />
      {/* lg */}
      <Wrapper className="hidden md:hidden lg:flex gap-[30px] ">
        <div className="w-[25%]">
          <Sidebar />
        </div>
        <div className="w-[75%]">
          <Aside />
        </div>
      </Wrapper>
      {/* md */}
      <Wrapper className="block md:block lg:hidden">
        <Aside />
      </Wrapper>
      {toggleModal && <Modal slug={slug} />}
    </>
  );
}
